package serialization

import androidx.compose.ui.geometry.Offset
import model.*
import model.axo.AxoModel
import model.classes.*

data class MongeSnapshot(
    val axoOverlayPoint: List<AxoOverlayPoint>,
    val axoOverlayLine: List<AxoOverlayLine>,
    val axoOverlaySegment: List<AxoOverlaySegment>,
    val pointsPudorys: List<Point3DPudorys>,
    val pointsNarys: List<Point3DNarys>,
    val pointsBokorys: List<Point3DBokorys>,
    val pointsAxo: List<Point3DAxo>,
    val linesPudorys: List<Line3DProjectionPudorys>,
    val linesNarys: List<Line3DProjectionNarys>,
    val linesBokorys: List<Line3DProjectionBokorys>,
    val linesAxo: List<Line3DProjectionAxo>,
    val segmentsPudorys: List<Segment2DPudorys>,
    val segmentsNarys: List<Segment2DNarys>,
    val segmentsBokorys: List<Segment2DBokorys>,
    val segmentsAxo: List<Segment2DAxo>,
    val sharedPoints3D: List<Point3D>,
    val lines3D: List<Line3D>,
    val segments3D: List<Segment3D>,
    val segmentSolids3D: List<SegmentSolid3D> = emptyList(),
    val planes3D: List<Plane3D>,
    val planeTracePudorys: List<PlaneTracePudorys>,
    val planeTraceNarys: List<PlaneTraceNarys>,
    val helpLinePudorys: List<HelpLinePudorys>,
    val planeTraceBokorys: List<PlaneTraceBokorys>,
    val helpLineNarys: List <HelpLineNarys>,
    val helpSegmentNarys:List <HelpSegmentNarys>,
    val helpSegmentPudorys:List <HelpSegmentPudorys>,
    val arcspudorys: List <Arc2DPudorys>,
    val arcsnarys: List <Arc2DNarys>,
    val arcsbokorys: List <Arc2DBokorys>,
    val arcsAxoOverlay: List<ArcAxoOverlay>,
    val circlesPudorys: List <ConicSectionPudorys>,
    val circlesNarys: List <ConicSectionNarys>,
    val circlesBokorys: List <ConicSectionBokorys>,
    val aidPointsLogical: List <AidPointLogical>,
    val conicsPudorys: List <ConicSectionPudorys>,
    val conicsNarys: List <ConicSectionNarys>,
    val conicsBokorys: List <ConicSectionBokorys>,
    val conicsAxo: List<ConicSectionAxo>,
    val conicInputPointsPudorys: Map<String, Triple<Offset, Offset, Offset>>,
    val conicInputPointsNarys: Map<String, Triple<Offset, Offset, Offset>>,
    val conicInputPointsBokorys: Map<String, Triple<Offset, Offset, Offset>>,
    val conicInputPointsAxo: Map<String,Triple<Offset, Offset, Offset>>,

    val conic3D: List<ConicSection3D>,
    val conicalSurface: List<ConicalSurface3D>,
    val cylinderSurface: List<CylindricalSurface3D>,
    val ruledSurfaces: List<RuledSurface3D> = emptyList(),
    val solidsOfRevolutionsNarys: List<SolidOfRevolutionNarys>,
    val solidsOfRevolutionsPudorys: List<SolidOfRevolutionPudorys>,
    // ── ELIPSA ──────────────────────────────────────────────
    val ellipseArcParams3D: Map<String, Pair<Float, Float>> = emptyMap(),
    val ellipseArcEnds3D:   Map<String, Pair<Offset3D, Offset3D>> = emptyMap(),
    val ellipseArcEnds: Map<String, Pair<Offset, Offset>> = emptyMap(),
    val ellipseArcMode: Map<String, ArcMode> = emptyMap(),

    // ── Po částech stylované kuželosečky (plná/čárkovaná) ───────
    val conicSegments: Map<String, model.ConicSegmentation> = emptyMap(),

    // ── PARABOLA ────────────────────────────────────────────
    val parabolaArcParams3D: Map<String, Pair<Float, Float>> = emptyMap(),
    val parabolaArcEnds3D:   Map<String, Pair<Offset3D, Offset3D>> = emptyMap(),
    val parabolaArcEnds: Map<String, Pair<Offset, Offset>> = emptyMap(),

    // ── HYPERBOLA (dvě větve) ──────────────────────────────
    val hyperbolaArcParams3D: Map<String, Pair<Pair<Float, Float>?, Pair<Float, Float>?>> = emptyMap(),
    val hyperbolaArcEnds3D:   Map<String, Pair<Pair<Offset3D, Offset3D>?, Pair<Offset3D, Offset3D>?>> = emptyMap(),

    // 2D řezy pro obě větve (unified)
    val hyperbolaArcBranch1: Map<String, Pair<Offset, Offset>> = emptyMap(),
    val hyperbolaArcBranch2: Map<String, Pair<Offset, Offset>> = emptyMap(),
    val hyperbolaInputsPudorys: Map<String, ConicInputHyperbolaPudorys> = emptyMap(),
    val hyperbolaInputsNarys:   Map<String, ConicInputHyperbolaNarys>   = emptyMap(),
    val hyperbolaInputsBokorys: Map<String, ConicInputHyperbolaBokorys> = emptyMap(),
    val hyperbolaInputsAxo: Map<String, ConicInputHyperbolaAxo> = emptyMap(),
    val spheres: List<SphereSurface3D>,
    val polygons: List<RegularPolygon3D>,
    val planePolygons2D: List<PlanePolygon2D> = emptyList(),
    val labelOffsetsNarys: Map<String, Offset> = emptyMap(),
    val labelOffsetsPudorys: Map<String, Offset> = emptyMap(),
    val labelOffsetsBokorys: Map<String, Offset> = emptyMap(),
    val labelOffsetsHelpNarys: Map<String, Offset> = emptyMap(),
    val labelOffsetsHelpPudorys: Map<String, Offset> = emptyMap(),
    val labelOffsetsPointsNarys: Map<String, Offset> = emptyMap(),
    val labelOffsetsPointsPudorys: Map<String, Offset> = emptyMap(),
    val labelOffsetsPointsBokorys: Map<String, Offset> = emptyMap(),
    val labelOffsetsPointsAxo: Map<String, Offset> = emptyMap(),
    val labelOffsetsTracePudorys: Map<String, Offset> = emptyMap(),
    val labelOffsetsTraceNarys: Map<String, Offset> = emptyMap(),
    val labelOffsetsTraceBokorys: Map<String, Offset> = emptyMap(),
    val labelOffsetsAOLine: Map<String, Offset> = emptyMap(),
    val labelOffsetsAOPoints: Map<String, Offset> = emptyMap(),
    val labelOffsetsAxoLines: Map<String, Offset> = emptyMap(),
    val labelOffsetsSegmentsPudorys: Map<String, Offset> = emptyMap(),
    val labelOffsetsSegmentsNarys: Map<String, Offset> = emptyMap(),
    val labelOffsetsSegmentsBokorys: Map<String, Offset> = emptyMap(),
    val labelOffsetsSegmentsAxo: Map<String, Offset> = emptyMap(),
    val labelOffsetsHelpSegmentsPudorys: Map<String, Offset> = emptyMap(),
    val labelOffsetsHelpSegmentsNarys: Map<String, Offset> = emptyMap(),
    val labelOffsetsAOSegments: Map<String, Offset> = emptyMap(),
    val labelOffsetsAidPoints: Map<String, Offset> = emptyMap(),
    val circleArcsPudorys: List<CircleArcPudorys> = emptyList(),
    val circleArcsNarys: List<CircleArcNarys> = emptyList(),
    val curves3D: List<Curve3D>,
    val curvesNarys: List<CurveNarys>,
    val curvesPudorys: List<CurvePudorys>,
    val curvesBokorys: List<CurveBokorys> = emptyList(),
    val curvesAxo: List<CurveAxo> = emptyList(),
    val intersectionGroups: List<IntersectionGroup> = emptyList(),
    val axoModel: AxoModel
)
